Task 12: add ExchangeRateProvider on getProductById
bainazarov/CrudShop pull request #13
Opened 2023-12-05 11:30 UTC by bainazarov

2023-12-05 11:40 UTC, GUR-ok commented on src/main/java/com/crudshop/demo/controller/product/ProductControllerImpl.java
> +        double priceInDollars = 0;
Тут убрать. сделать через advice

2023-12-05 11:41 UTC, GUR-ok commented on src/main/java/com/crudshop/demo/util/ExchangeRateProvider.java
> +            throw new RuntimeException("Ошибка при парсинге файла");
давай просто залогируем ошибку. а вернем дефолтное значение, которое в конфигах пропишем в application-properties

2023-12-06 04:59 UTC, GUR-ok requested changes

2023-12-06 04:59 UTC, GUR-ok commented on src/main/java/com/crudshop/demo/util/ExchangeRateProvider.java
> +            ObjectMapper objectMapper = new ObjectMapper();
final при объявлении переменных

2023-12-06 04:59 UTC, GUR-ok commented on src/main/java/com/crudshop/demo/util/ExchangeRate.java
> +@Data
value вместо data или поле сделать final

2023-12-06 04:59 UTC, GUR-ok commented on src/main/java/com/crudshop/demo/controller/document/DocumentController.java
> +    HttpEntity<ByteArrayResource> downloadFile(@RequestParam String fileName) throws IOException;
throws IOException { не должно быть

2023-12-06 04:59 UTC, GUR-ok commented on src/main/java/com/crudshop/demo/controller/document/DocumentControllerImpl.java
> -    public HttpEntity<ByteArrayResource> downloadFile(@RequestParam(required = true) String fileName) throws IOException {
throws IOException { не должно быть. Обработай try-catch и если надо расширь текущий try-catch и в коде и по типу исключения

2023-12-06 04:59 UTC, GUR-ok commented on src/main/java/com/crudshop/demo/controller/document/DocumentControllerImpl.java
>          return new HttpEntity<>(new ByteArrayResource(resource.getContentAsByteArray()), header);
А зачем ты создаешь новый ресурс из другого ресурса? Нельзя создавать сразу ByteArrayResource?

2023-12-06 08:32 UTC, bainazarov commented on src/main/java/com/crudshop/demo/controller/document/DocumentControllerImpl.java
>          return new HttpEntity<>(new ByteArrayResource(resource.getContentAsByteArray()), header);
Так мне же header надо вернуть еще, при ByteArrayResource мне придется создавать лишнее поле

2023-12-06 11:48 UTC, GUR-ok commented on src/main/java/com/crudshop/demo/controller/document/DocumentControllerImpl.java
> +        try {
у тебя два try. сделай один общий. про второе поле не понял, обсудим завтра в офисе

2023-12-07 04:54 UTC, GUR-ok commented on src/main/java/com/crudshop/demo/controller/document/DocumentControllerImpl.java
>          return new HttpEntity<>(new ByteArrayResource(resource.getContentAsByteArray()), header);
хедер не относится к ByteArrayResource

2023-12-07 04:55 UTC, GUR-ok approved these changes

2023-12-07 06:37 UTC, merged